#!/usr/bin/env node

/**
 * yougile-setup — One-time board setup for new projects.
 *
 * Creates a YouGile board with standard columns and stickers,
 * then writes all IDs into the project's config.yaml.
 *
 * Usage:
 *   node yougile-setup/dist/index.js \
 *     --project-name "Family Cinema" \
 *     --project-id "uuid" \
 *     --modules "frontend,backend" \
 *     --config-path ./config.yaml
 *
 * Environment:
 *   YOUGILE_API_KEY — required
 *
 * Output: JSON to stdout (same pattern as docmost-sync)
 */

import { readFile, writeFile } from 'fs/promises';
import { resolve } from 'path';

// ─── Types ───────────────────────────────────────────────

interface SetupResult {
  success: boolean;
  board: { id: string; title: string } | null;
  columns: Record<string, string>;   // name → id
  stickers: {
    task_type: { id: string; states: Record<string, string> };
    module: { id: string; states: Record<string, string> };
    source: { id: string; states: Record<string, string> };
  } | null;
  configUpdated: boolean;
  errors: string[];
}

// ─── Standard columns ───────────────────────────────────

// Column order as it should appear on the board (left to right).
// YouGile displays the LAST created column FIRST, so we reverse when creating.
const STANDARD_COLUMNS = [
  'UserRequests',
  'Backlog',
  'Reopened',
  'InWork',
  'DevDone',
  'ReadyToTest',
  'Testing',
  'ToRelease',
  'Done',
];

// ─── Standard stickers ──────────────────────────────────

const STANDARD_STICKERS = [
  {
    name: 'Type',
    states: ['feature', 'bug', 'task'],
    colors: ['#22c55e', '#ef4444', '#3b82f6'],
  },
  {
    name: 'Source',
    states: ['user', 'agent'],
    colors: ['#8b5cf6', '#f59e0b'],
  },
];

// ─── API client ──────────────────────────────────────────

const API_BASE = 'https://yougile.com/api-v2';

async function apiCall(
  method: string,
  endpoint: string,
  apiKey: string,
  body?: Record<string, unknown>
): Promise<unknown> {
  const url = `${API_BASE}${endpoint}`;
  const headers: Record<string, string> = {
    'Authorization': `Bearer ${apiKey}`,
    'Content-Type': 'application/json',
  };

  const res = await fetch(url, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`API ${method} ${endpoint}: ${res.status} ${text}`);
  }

  return res.json();
}

// ─── Setup functions ─────────────────────────────────────

async function createBoard(
  apiKey: string,
  projectId: string,
  title: string
): Promise<string> {
  const data = await apiCall('POST', '/boards', apiKey, {
    title,
    projectId,
  }) as { id: string };
  return data.id;
}

async function createColumn(
  apiKey: string,
  boardId: string,
  title: string,
  color?: string
): Promise<string> {
  const body: Record<string, unknown> = { title, boardId };
  if (color) body.color = color;
  const data = await apiCall('POST', '/columns', apiKey, body) as { id: string };
  return data.id;
}

async function createSticker(
  apiKey: string,
  name: string,
  states: Array<{ name: string; color: string }>
): Promise<{ stickerId: string; stateIds: Record<string, string> }> {
  // Create the sticker
  const sticker = await apiCall('POST', '/string-stickers', apiKey, {
    name,
  }) as { id: string };

  const stateIds: Record<string, string> = {};

  // Create states for the sticker
  for (const state of states) {
    const stateData = await apiCall(
      'POST',
      `/string-stickers/${sticker.id}/states`,
      apiKey,
      { name: state.name, color: state.color }
    ) as { id: string };
    stateIds[state.name] = stateData.id;
  }

  return { stickerId: sticker.id, stateIds };
}

// ─── Config.yaml update ─────────────────────────────────

async function updateConfigYaml(
  configPath: string,
  result: SetupResult
): Promise<void> {
  let content: string;
  try {
    content = await readFile(configPath, 'utf-8');
  } catch {
    console.error(`config.yaml not found at ${configPath}, creating yougile section only`);
    content = '';
  }

  // Build the yougile YAML block
  const columns = result.columns;
  const stickers = result.stickers;

  const yougileBlock = `
# YouGile (auto-generated by yougile-setup)
yougile:
  api_base: "https://yougile.com/api-v2"
  project_id: "${result.board ? '' : ''}"
  board_id: "${result.board?.id || ''}"
  columns:
    user_requests: "${columns['UserRequests'] || ''}"
    backlog: "${columns['Backlog'] || ''}"
    in_work: "${columns['InWork'] || ''}"
    dev_done: "${columns['DevDone'] || ''}"
    ready_to_test: "${columns['ReadyToTest'] || ''}"
    testing: "${columns['Testing'] || ''}"
    to_release: "${columns['ToRelease'] || ''}"
    reopened: "${columns['Reopened'] || ''}"
    done: "${columns['Done'] || ''}"
  stickers:
    task_type:
      id: "${stickers?.task_type.id || ''}"
      states:
        feature: "${stickers?.task_type.states['feature'] || ''}"
        bug: "${stickers?.task_type.states['bug'] || ''}"
        task: "${stickers?.task_type.states['task'] || ''}"
    module:
      id: "${stickers?.module.id || ''}"
      states: ${stickers?.module.states ? JSON.stringify(stickers.module.states).replace(/"/g, '"') : '{}'}
    source:
      id: "${stickers?.source.id || ''}"
      states:
        user: "${stickers?.source.states['user'] || ''}"
        agent: "${stickers?.source.states['agent'] || ''}"
`;

  // Replace existing yougile section or append
  if (content.includes('yougile:')) {
    // Replace from "yougile:" to the next top-level key or end
    const yougileStart = content.indexOf('yougile:');
    // Find next top-level key (line starting without spaces, containing ':')
    const afterYougile = content.substring(yougileStart + 1);
    const nextKeyMatch = afterYougile.match(/\n[a-z]/);
    if (nextKeyMatch && nextKeyMatch.index !== undefined) {
      const yougileEnd = yougileStart + 1 + nextKeyMatch.index;
      content = content.substring(0, yougileStart) + yougileBlock.trim() + '\n\n' + content.substring(yougileEnd + 1);
    } else {
      content = content.substring(0, yougileStart) + yougileBlock.trim() + '\n';
    }
  } else {
    content = content + '\n' + yougileBlock;
  }

  await writeFile(configPath, content, 'utf-8');
}

// ─── CLI ─────────────────────────────────────────────────

function parseArgs(argv: string[]): {
  projectName: string;
  projectId: string;
  modules: string[];
  configPath: string;
} {
  const args: Record<string, string> = {};
  for (let i = 2; i < argv.length; i++) {
    const arg = argv[i];
    if (arg.startsWith('--') && i + 1 < argv.length) {
      args[arg.slice(2)] = argv[++i];
    }
  }

  if (!args['project-name']) throw new Error('--project-name is required');
  if (!args['project-id']) throw new Error('--project-id is required');

  return {
    projectName: args['project-name'],
    projectId: args['project-id'],
    modules: (args['modules'] || 'frontend,backend').split(',').map(s => s.trim()),
    configPath: resolve(args['config-path'] || './config.yaml'),
  };
}

// ─── Main ────────────────────────────────────────────────

async function main(): Promise<void> {
  const apiKey = process.env.YOUGILE_API_KEY;
  if (!apiKey) {
    const errorResult: SetupResult = {
      success: false,
      board: null,
      columns: {},
      stickers: null,
      configUpdated: false,
      errors: ['YOUGILE_API_KEY environment variable is required'],
    };
    console.log(JSON.stringify(errorResult, null, 2));
    process.exit(1);
  }

  let parsed;
  try {
    parsed = parseArgs(process.argv);
  } catch (err) {
    const errorResult: SetupResult = {
      success: false,
      board: null,
      columns: {},
      stickers: null,
      configUpdated: false,
      errors: [String(err)],
    };
    console.log(JSON.stringify(errorResult, null, 2));
    process.exit(1);
  }

  const result: SetupResult = {
    success: false,
    board: null,
    columns: {},
    stickers: null,
    configUpdated: false,
    errors: [],
  };

  try {
    // Step 1: Create board
    console.error(`Creating board "${parsed.projectName}"...`);
    const boardId = await createBoard(apiKey, parsed.projectId, parsed.projectName);
    result.board = { id: boardId, title: parsed.projectName };
    console.error(`Board created: ${boardId}`);

    // Step 2: Create columns (reversed — YouGile shows last-created first)
    console.error('Creating columns...');
    const columnsReversed = [...STANDARD_COLUMNS].reverse();
    for (const colName of columnsReversed) {
      try {
        const colId = await createColumn(apiKey, boardId, colName);
        result.columns[colName] = colId;
        console.error(`  ✓ ${colName}: ${colId}`);
      } catch (err) {
        result.errors.push(`Column ${colName}: ${err}`);
        console.error(`  ✗ ${colName}: ${err}`);
      }
    }

    // Step 3: Create stickers (check existing first)
    console.error('Setting up stickers...');

    // Fetch existing stickers to avoid duplicates
    let existingStickers: Array<{ id: string; name: string; states?: Array<{ id: string; name: string }> }> = [];
    try {
      const stickersData = await apiCall('GET', '/string-stickers', apiKey) as { content?: Array<{ id: string; name: string; states?: Array<{ id: string; name: string }> }> };
      existingStickers = stickersData.content || [];
      console.error(`  Found ${existingStickers.length} existing stickers`);
    } catch {
      console.error('  Could not fetch existing stickers, creating all from scratch');
    }

    // Helper: find existing sticker by name (case-insensitive)
    function findExisting(name: string) {
      return existingStickers.find(s => s.name.toLowerCase() === name.toLowerCase());
    }

    // Helper: get or create sticker
    async function getOrCreateSticker(
      key: string,
      name: string,
      states: Array<{ name: string; color: string }>
    ): Promise<{ stickerId: string; stateIds: Record<string, string> }> {
      const existing = findExisting(name);
      if (existing) {
        console.error(`  ↳ "${name}" already exists (${existing.id}), reusing`);
        const stateIds: Record<string, string> = {};
        // Map existing states
        for (const state of (existing.states || [])) {
          stateIds[state.name] = state.id;
        }
        // Create missing states
        for (const wanted of states) {
          if (!stateIds[wanted.name]) {
            try {
              const stateData = await apiCall(
                'POST',
                `/string-stickers/${existing.id}/states`,
                key,
                { name: wanted.name, color: wanted.color }
              ) as { id: string };
              stateIds[wanted.name] = stateData.id;
              console.error(`    + added state "${wanted.name}"`);
            } catch (err) {
              console.error(`    ✗ failed to add state "${wanted.name}": ${err}`);
            }
          }
        }
        return { stickerId: existing.id, stateIds };
      }
      // Create new
      return createSticker(key, name, states);
    }

    try {
      // Type sticker
      const typeSticker = await getOrCreateSticker(apiKey, 'Type', [
        { name: 'feature', color: '#22c55e' },
        { name: 'bug', color: '#ef4444' },
        { name: 'task', color: '#3b82f6' },
      ]);
      console.error(`  ✓ Type: ${typeSticker.stickerId}`);

      // Module sticker (dynamic based on --modules)
      const moduleStates = parsed.modules.map((m, i) => ({
        name: m,
        color: ['#f59e0b', '#8b5cf6', '#06b6d4', '#ec4899'][i % 4],
      }));
      const moduleSticker = await getOrCreateSticker(apiKey, 'Module', moduleStates);
      console.error(`  ✓ Module: ${moduleSticker.stickerId} (${parsed.modules.join(', ')})`);

      // Source sticker
      const sourceSticker = await getOrCreateSticker(apiKey, 'Source', [
        { name: 'user', color: '#8b5cf6' },
        { name: 'agent', color: '#f59e0b' },
      ]);
      console.error(`  ✓ Source: ${sourceSticker.stickerId}`);

      result.stickers = {
        task_type: { id: typeSticker.stickerId, states: typeSticker.stateIds },
        module: { id: moduleSticker.stickerId, states: moduleSticker.stateIds },
        source: { id: sourceSticker.stickerId, states: sourceSticker.stateIds },
      };
    } catch (err) {
      result.errors.push(`Stickers: ${err}`);
      console.error(`  ✗ Stickers error: ${err}`);
    }

    // Step 4: Update config.yaml
    console.error(`Updating config: ${parsed.configPath}`);
    try {
      await updateConfigYaml(parsed.configPath, result);
      result.configUpdated = true;
      console.error('  ✓ config.yaml updated');
    } catch (err) {
      result.errors.push(`Config update: ${err}`);
      console.error(`  ✗ Config error: ${err}`);
    }

    result.success = result.errors.length === 0;
  } catch (err) {
    result.errors.push(`Fatal: ${err}`);
  }

  // Output JSON summary to stdout
  console.log(JSON.stringify(result, null, 2));
  process.exit(result.success ? 0 : 1);
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
