#!/bin/sh
# install-sidecar.sh — set up the per-developer mTLS tunnel to a shared VPS graph (POSIX).
#
# The tunnel is what makes "zero skill / zero MCP changes" possible: it holds THIS developer's
# client certificate (the revocable "API key"), opens an mTLS connection to the VPS ghostunnel
# gateway, and exposes a PLAINTEXT bolt://localhost:<sidecar_port> that .mcp.json points at —
# exactly as a local container would. Per project scope.
#
#   install-sidecar.sh --project-scope SCOPE --host graph.example.com --gateway-port 7687 \
#       --sidecar-port 3700 --cert PATH --key PATH --cacert PATH [--start]
#
# Without --start it only writes the launcher and prints how to run it; with --start it also
# launches the tunnel in the background (nohup) and writes a pidfile. Idempotent.
set -eu

SCOPE=""; HOST=""; GW_PORT=""; SIDECAR_PORT=""; CERT=""; KEY=""; CACERT=""; START=0
while [ $# -gt 0 ]; do
  case "$1" in
    --project-scope) SCOPE="$2"; shift 2 ;;
    --host)          HOST="$2"; shift 2 ;;
    --gateway-port)  GW_PORT="$2"; shift 2 ;;
    --sidecar-port)  SIDECAR_PORT="$2"; shift 2 ;;
    --cert)          CERT="$2"; shift 2 ;;
    --key)           KEY="$2"; shift 2 ;;
    --cacert)        CACERT="$2"; shift 2 ;;
    --start)         START=1; shift ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done
for v in SCOPE HOST GW_PORT SIDECAR_PORT CERT KEY CACERT; do
  eval "val=\$$v"; [ -n "$val" ] || { echo "Missing required argument (--$(echo "$v" | tr 'A-Z_' 'a-z-'))" >&2; exit 2; }
done

# Expand ~ in cert paths.
expand() { case "$1" in "~/"*) printf '%s' "$HOME/${1#~/}" ;; *) printf '%s' "$1" ;; esac; }
CERT=$(expand "$CERT"); KEY=$(expand "$KEY"); CACERT=$(expand "$CACERT")
for f in "$CERT" "$KEY" "$CACERT"; do
  [ -f "$f" ] || { echo "ERROR: certificate file not found: $f" >&2; echo "Ask the graph admin to issue you one: issue-client-cert.sh <your-id>" >&2; exit 1; }
done

if ! command -v ghostunnel >/dev/null 2>&1; then
  cat >&2 <<'EOF'
ERROR: 'ghostunnel' is not installed. Install it, then re-run:
  macOS:        brew install ghostunnel
  Linux (Go):   go install github.com/ghostunnel/ghostunnel@latest
  Or grab a release binary: https://github.com/ghostunnel/ghostunnel/releases
EOF
  exit 1
fi

SIDE_DIR="${NACL_HOME:-$HOME/.nacl}/sidecar"
mkdir -p "$SIDE_DIR"
LAUNCHER="$SIDE_DIR/$SCOPE.sh"
PIDFILE="$SIDE_DIR/$SCOPE.pid"
LOGFILE="$SIDE_DIR/$SCOPE.log"

# ghostunnel client: listen locally (plaintext bolt), forward over mTLS to the VPS gateway.
cat > "$LAUNCHER" <<EOF
#!/bin/sh
# Auto-generated by install-sidecar.sh for project scope: $SCOPE
exec ghostunnel client \\
  --listen "localhost:$SIDECAR_PORT" \\
  --target "$HOST:$GW_PORT" \\
  --cert "$CERT" --key "$KEY" --cacert "$CACERT" \\
  --connect-timeout 10s
EOF
chmod +x "$LAUNCHER"
echo "Sidecar launcher written: $LAUNCHER" >&2
echo "  local bolt socket: bolt://localhost:$SIDECAR_PORT  →  mTLS  →  $HOST:$GW_PORT" >&2

if [ "$START" = "1" ]; then
  if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
    echo "Sidecar already running (pid $(cat "$PIDFILE"))." >&2
  else
    nohup "$LAUNCHER" >"$LOGFILE" 2>&1 &
    echo $! > "$PIDFILE"
    echo "Sidecar started (pid $(cat "$PIDFILE")); logs: $LOGFILE" >&2
  fi
else
  echo "Run it with:  $LAUNCHER   (or re-run this with --start)" >&2
fi

printf '\nNACL_SIDECAR_RESULT: status=READY scope=%s listen=localhost:%s target=%s:%s\n' \
  "$SCOPE" "$SIDECAR_PORT" "$HOST" "$GW_PORT"
